### ISSUE TITLE
Headings lose color when exporting to PDF

### ISSUE THREAD

**Issue by patbornay** [Seraaron/agora-obsidian-theme#2]
There seems to be a issue with heading coming out as an off-white color when exporting to a PDF. This also seems to happen regardless of dark-mode of light-mode.

To recreate:
create a note with various headings and export the note to PDF

Example: 
![image](https://user-images.githubusercontent.com/26018905/150312360-9c961107-ad99-495c-b708-0862f52a80af.png)

**Comment by Seraaron** [comment]
Hiya, I'm not sure this is an issue that I can solve.

So what's happening is this: The colored headings are only visible in the markdown editing mode for easy visual recognition of where you are in a page while editing, and then the colors of those same headings in preview mode are supposed to all switch to black (or off-white if you're using dark mode, which you are). This is all intentional design, so that won't be changing. 

But I think the problem you're really getting is with your markdown to pdf exporter, it's not picking up the background color of the obsidian document theme.

Can you try exporting in another theme in darkmode and see if a similar issue arises?

**Comment by patbornay** [comment]
Ah okay, yeah it works fine once I switch over to light mode and then export, thanks.
![image](https://user-images.githubusercontent.com/26018905/150525976-d71dc995-88b9-4ce4-8587-b41199600138.png)

I tried it with another theme (shimmering focus) here's the outcome
Dark mode (looks okay)
![image](https://user-images.githubusercontent.com/26018905/150525649-ec304268-0b47-4779-a19d-5f04d2499359.png)
Light mode
![image](https://user-images.githubusercontent.com/26018905/150525736-af404e32-7367-46e0-95b2-52a446d5e5ec.png)

**Comment by Seraaron** [comment]
Hm... strange. I'll have a poke around the code, but I can't guarantee that I'll be able to find a fix. It might be worth reporting this as a separate issue on the obsidian github repo too? Or on the repo of the markdown exporter plugin? If you specifically want to export in the dark mode theme, with black background pages and such.

**Comment by patbornay** [comment]
Gotcha, thanks mate.
